### PR TITLE
Cleanup eclipse and added maven support

### PR DESCRIPTION
**Pull request by mrmx**

### CODE REVIEW

**Comment by justmoon** [comment]
Works! LGTM

For future reference, the license should indeed be Apache 2.0, so we should work towards all repos reflecting that.

**Comment by mrmx** [comment]
Yes I noticed no license was indicated in the other repos, so great to know it! Ready to merge!

**Comment by adrianhopebailie** [comment]
Have added you as a collaborator, you should be able to merge

**Comment by mrmx** [comment]
Great! Thanks! Also the java-ilp-core needs merge ;)

**Pull request merged**
